# Generated by Django 5.2.7 on 2025-10-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_bio_customuser_department_customuser_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gparecord',
            options={},
        ),
        migrations.AddField(
            model_name='gparecord',
            name='cgpa',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gparecord',
            name='semester',
            field=models.CharField(max_length=100),
        ),
    ]
